### ISSUE TITLE
书籍图片无法显示

### ISSUE THREAD

**Issue by yangyuan6956873** [banmajio/Library#1]
通过后台添加的图书，切回到主页面时可以显示，但是电脑重启后再次打开项目，图片就无法显示了。是需要吧图片放到一个特定的文件夹里吗？

**Comment by banmajio** [comment]
项目太久了，毕业设计的项目，不确定你遇到的问题是什么原因造成的。如果没记错的话好像是tomcat的哪个版本可能会造成这种情况，添加的图片没有写到本地路径里，而是在一个临时的文件夹里。重启后，临时文件夹过期，图片就无法加载了。你可以百度一下这方面的内容，好久不用了已经忘了怎么设置了。

**Comment by yangyuan6956873** [comment]
好的，谢谢

**Comment by yangyuan6956873** [comment]
我看了一下数据库里的信息，bookdb表中的path列保存的是日期信息像是2020-5-21，请问这样的是对的吗？

**Comment by yangyuan6956873** [comment]
他这个path列的值保存的是日期信息，这样是对的吗？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"banmajio"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 上午10:56
收件人:&nbsp;"banmajio/Library"<Library@noreply.github.com&gt;;
抄送:&nbsp;"杨.."<996155402@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [banmajio/Library] 书籍图片无法显示 (#1)





 
项目太久了，毕业设计的项目，不确定你遇到的问题是什么原因造成的。如果没记错的话好像是tomcat的哪个版本可能会造成这种情况，添加的图片没有写到本地路径里，而是在一个临时的文件夹里。重启后，临时文件夹过期，图片就无法加载了。你可以百度一下这方面的内容，好久不用了已经忘了怎么设置了。

**Comment by banmajio** [comment]
不好意思，忘记了，现在本地没有这个环境了，所以看不了，你自己研究一下吧！
